#!/usr/bin/env node
/* Content build step.
   ---------------------
   Reads markdown files from /content/projects/*.md, parses YAML
   frontmatter via gray-matter, and emits a single client-safe JS
   module at src/lib/_projectContent.generated.js mapping slug → data.

   Why: projects.js is imported by the client-side Sidebar, so it
   can't pull `fs` at module load. Pre-generating the data into a
   plain JS module sidesteps the bundler-vs-Node split and keeps
   the CMS workflow (edit .md → restart dev → site updates).

   Wired up via the `predev` and `prebuild` npm scripts. */

import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import matter from "gray-matter";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content", "projects");
const OUT_FILE = path.join(ROOT, "src", "lib", "_projectContent.generated.js");

function loadAll() {
  if (!fs.existsSync(CONTENT_DIR)) return {};
  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));
  const out = {};
  for (const file of files) {
    const slug = path.basename(file, ".md");
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf8");
    const { data } = matter(raw);
    out[slug] = data;
  }
  return out;
}

const data = loadAll();
const body =
  "/* AUTO-GENERATED by scripts/buildContent.mjs — do not edit. */\n" +
  "export const projectContent = " +
  JSON.stringify(data, null, 2) +
  ";\n";

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, body);

const slugs = Object.keys(data);
console.log(
  `[buildContent] wrote ${slugs.length} project${slugs.length === 1 ? "" : "s"}: ${slugs.join(", ")}`
);
